### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by ghost** [lephong/mulrel-nel#2]
I executed the script from mulrel-nel/nel:

```
export PYTHONPATH=$PYTHONPATH:../
python -u -m nel.main --mode train --n_rels 3 --mulrel_type ment-norm --model_path model
```

But a error was happen:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/work/mulrel-nel/nel/main.py", line 159, in <module>
    ranker.train(conll.train, dev_datasets, config)
  File "/root/work/mulrel-nel/nel/ed_ranker.py", line 327, in train
    loss = loss.cpu().data.numpy()[0]
IndexError: too many indices for array
```

How to fix it?

**Comment by ghost** [comment]
I fixed it by myself. 

According to <a href="https://github.com/pytorch/pytorch/issues/6921">this issue</a>, we don't need [0], so just replace it to:

`loss = loss.cpu().data.numpy()`

and it works.

**Comment by ghost** [comment]
I'm not sure, but maybe  it's related to Pytorch version.
